### ISSUE TITLE
TV out stuck, no refresh on tv

### ISSUE THREAD

**Issue by fbis251** [teamacid/android_device_samsung_galaxys4gmtd#12]
TV out enables fine, but only the very first frame gets displayed on the TV. The image doesn't refresh.

**Comment by maxfierke** [comment]
This is because tvouthack has not been compiled in yet. I need to make some changes to what airfluip did first.

**Comment by maxfierke** [comment]
It should be fixed in 4579d69c2d7f8bd14a6bcfe6d101b943baab1c64. Please confirm.

**Comment by fbis251** [comment]
I'll run a build and get back to you

**Comment by fbis251** [comment]
No luck:
http://pastebin.com/iY1ZSQz2

It's still doing the same thing

**Comment by bhundven** [comment]
Backported aries tvout binaries teamacid/proprietary_vendor_samsung@68c0564313e60477b4abb4d132a929635bbce5e3

Fixes tvout functionality.

One problem fixed, Which brings a new bug. (/me thinks wack-a-mole)

:sigh:

Closing this bug, opening #29
