### ISSUE TITLE
Softkey backlights stay on when the screen is on

### ISSUE THREAD

**Issue by fbis251** [teamacid/android_device_samsung_galaxys4gmtd#14]
It only occurs when video is displayed on the screen. In all other cases the backlights time out and turn off properly even though the screen remains on.

**Comment by maxfierke** [comment]
Is this issue also present in the CM9 builds?

jt1134 made some changes to cypress-touchkey on the ICS branch and I'm wondering if they fixed it. If so, I will cherry-pick those changes back into the gingerbread branch.

**Comment by fbis251** [comment]
Yes, CM9 builds also have this. This doesn't only happen with video playback either.

**Comment by fbis251** [comment]
Closed on device tree since this is most likely a kernel issue.

https://github.com/teamacid/android_kernel_galaxys4gmtd/issues/15
