### ISSUE TITLE
Low Power Mode Broken

### ISSUE THREAD

**Issue by Eollie** [teamacid/android_device_samsung_galaxys4gmtd#19]
If you power the phone off to charge in offline mode it will not power back on until the phone is unplugged. Offline charging seems to be not working either currently. I do not know how to get logs of this so a basic explanation would be appreciated if logs are requested. 

How to replicate: power down the phone via the power button or remove battery. Plug phone into either usb from computer or wall charger. Let phone go into offline charging and then push power button to power phone back on. It will not attempt to reboot the phone. Typically holding the power button for a second or two will power the phone on. But nothing happens and eventually it will reset because you are holding the power button in.

**Comment by Fluidification** [comment]
so if you kill your battery, then you are screwed?

**Comment by jt1134** [comment]
lpm binary compilation is disabled as it does not compile in ICS. Best bet is to port in aosp charger binary that devices like gnex/sgs2 use.

**Comment by jt1134** [comment]
airfluip1, you can still boot into download mode manually with a dead battery and flash a rom without this bug :p

**Comment by Fluidification** [comment]
i'll see if we can port, just I don't want my phone to be a brick

**Comment by ghost** [comment]
Also recovery should charge the device. But I like plugging the phone in turning it off and letting it charge for thirty minutes for a faster charge.

**Comment by Fluidification** [comment]
this'd be a android_device thing right?

**Comment by Fluidification** [comment]
this is a kernel issue.

Can someone who has good driver porting skills port otg drivers from here?
https://github.com/CyanogenMod/android_kernel_samsung_crespo/tree/ics/drivers/usb/otg

**Comment by maxfierke** [comment]
Nope. 

It's an issue with playlpm. I just got my build system configured for CM9. I'm looking into fixing playlpm. This is why we switched to the open source version, so we have the ability to fix things when they break.

**Comment by ghost** [comment]
Max in cm7 offline charging worked but it wouldnt let you power back on. I initially was going to report that but when double checking how it acted I noticed offline wasnt working in cm9/aokp. Thanks for looking at this.

**Comment by maxfierke** [comment]
Yeah, either jt1134 or bryan had an issue compiling playlpm in CM9, so they removed it from the build process. The reason it freezes is because low power mode looks for playlpm in /system/bin, but since it was never compiled, it's not there.

**Comment by Fluidification** [comment]
got an alternative?

Also, you could try to build stock AOSP to do so?

**Comment by jt1134** [comment]
There's an alternative already in aosp. Planning on porting that soon.
On Jun 25, 2012 5:41 PM, "Airfluip" <
reply@reply.github.com>
wrote:

**Comment by Fluidification** [comment]
:p  btw, is it getting rid of those laggy qmgs?

**Comment by maxfierke** [comment]
Is the AOSP version different from the GPL'd version from replicant?

**Comment by bhundven** [comment]
afaikt, this bad boy is fixed. GJ JT!
5434312e0f9f75835009375c0a64235d0005ad70
