### ISSUE TITLE
Video Recording Fails

### ISSUE THREAD

**Issue by fbis251** [teamacid/android_device_samsung_galaxys4gmtd#2]
Recording videos with any app (the camcorder app included, 3rd party apps from the market) fails after a few seconds and the created video file is 0bytes in size.

**Comment by maxfierke** [comment]
Could someone try applying these two patches to the device tree, compile a fresh build (make clobber and all that) and then test to see if it fixes the video encoding issue?

http://pastebin.com/1zEQJfJT

These are the only notable differences between our version of sec_mm and epicmtd's.

**Comment by maxfierke** [comment]
I forgot, here's the stacktrace. It's not super helpful besides pointing to the affected OMX functions

http://pastebin.com/Hbgetv3p

**Comment by maxfierke** [comment]
Fixed by a combination of 9b3f5370194403cf6018cdcf47ade2e5be69c646 on this tree and 32e2aee4c52a905d2057042fbaa216fb5d33b284, a482ee5c0aab5eecd0bb990dcd2537c65340a72d, 39cf49fc8d00d9bf61e31126c53cf0cd960f6fc1, and 7fef605078c0aba5657378bda5b2510c36d4235e on the kernel tree.
