### ISSUE TITLE
Plugging in USB causes AOKP to lockup

### ISSUE THREAD

**Issue by iamperson347** [teamacid/android_device_samsung_galaxys4gmtd#23]
I thought that I fixed this when I did a factory reset + /system format, essentially starting fresh, but it seems the problem still persist. If you plug in a USB cable that is connected to a computer, the computer detects the device but the phone becomes completely unresponsive. If you wait until the phone reboots, Android will detect the USB plugged in as normal (icon in the notification bar), but when you unplug it, the phone again locks up until it reboots. This is on AOKP.

**Comment by bhundven** [comment]
Could someone else confirm this issue?

Also, do this:

```
cat /proc/kmsg > /data/livekmsg
```

In a terminal, then plugin usb.

This should get the crash message from the kernel as it happens.

Then paste the livekmsg here.
