### ISSUE TITLE
Voodoo Sound not working (AOKP. CM9?)

### ISSUE THREAD

**Issue by iamperson347** [teamacid/android_device_samsung_galaxys4gmtd#24]
Max said this is known, but just reporting it here to keep tabs on the issue. Voodoo sound does not apply the amplifier gain to the ICS audio stream. Other settings may not work as well. This is with the Voodoo free app and AOKP.

**Comment by maxfierke** [comment]
Just to note: DSPManager on CM9 integrates the features of the voodoo free app (in the WM8994 tab). If AOKP has DSPManager, you should use that. Once we fix voodoo sound, I mean.

**Comment by maxfierke** [comment]
Fixed in teamacid/android_kernel_galaxys4gmtd@5b0dc30bfa027434f2ba34d6f6faa123d71b8cb0
