### ISSUE TITLE
Power button shutter takes picture but shuts phone screen CM9/7

### ISSUE THREAD

**Issue by Fluidification** [teamacid/android_device_samsung_galaxys4gmtd#26]
If you take a picture using the power button shutter on both CM9 and CM7 camera, the screen goes to sleep but also takes the picture.
1. Go to camera settings
2. Set power button shutter
3. take picture using power button
4. Screen will shut off.
5. Press power button again and unlock your phone
6. Picture will have been taken

Expected, it should just take the picture. Output, phone to sleep and picture taken

Android 4.0.4 and Android 2.3.7
CyanogenMod 9 Unofficial all releases
CyanogenMod 7 Unofficial all releases

here is a logcat
http://pastebin.com/tm0erWph

**Comment by jeffsf** [comment]
Unable to replicate in current CM9 builds.

I have not checked CM7

**Comment by Fluidification** [comment]
Well, the bug might have been fixed in cm 9.1.0 by the CM team and not Acid.

**Comment by maxfierke** [comment]
Closing because it looks like an upstream issue.
