### ISSUE TITLE
Phone is stuck Unlocking SIM Card

### ISSUE THREAD

**Issue by ovacikar** [teamacid/android_device_samsung_galaxys4gmtd#27]
Hello ,

I always put a PIN on my SIM card and this rom gets stuck unlocking the SIM card. In the background I can see it has T-Mobile service, got a voicemail alert but the screen is vlocked from doing anything because of the Unlocking SIM prompt.

This is for CM7 20120704 release.

Workaround: turn the phone off, put the sim card to another phone and remove PIN protection .

**Comment by Fluidification** [comment]
It works fine on CM9 though.

I tested.

**Comment by maxfierke** [comment]
This may be an upstream CM7 bug. I'll look into it.

**Comment by ovacikar** [comment]
I have been using CM7 on both Motorola Bravo (Kobe) and Atrix 4G (Olympus) and without this issue. Can anyone confirm by putting a pin on their SIM?

**Comment by maxfierke** [comment]
I meant it may be an upstream CM7 bug for Samsung devices, i.e. those using
the Samsung RIL.
