### ISSUE TITLE
GPS does not function at all

### ISSUE THREAD

**Issue by jeffsf** [teamacid/android_device_samsung_galaxys4gmtd#31]
Using the Aries kernel on a CM9 build, the GPS system does not respond to standard user apps or to AngryGPS (app-wrapped GPS test).

_Note: This was observed when the RIL was not functioning. May be related to lack of an operational RIL_

**Comment by jeffsf** [comment]
Excerpt from CM9 (Herring) startup (GPS _does_ work for this build)

<6>[   11.496903] init: command 'chown' r=-2
<6>[   11.497067] init: command 'chown' r=0
<6>[   11.497144] init: command 'setprop' r=0
<6>[   11.497163] init: processing action 0x35658 (queue_property_triggers)
<6>[   11.497232] init: command 'queue_property_triggers' r=0
<6>[   11.497245] init: processing action 0x2b778 (nonencrypted)
<5>[   11.530421] init: starting 'gpsd'
<5>[   11.535575] init: starting 'orientationd'
<5>[   11.539896] init: starting 'geomagneticd'
<5>[   11.541077] init: starting 'tvout'
<6>[   11.541336] init: command 'class_start' r=0
<6>[   11.541382] init: processing action 0x2bea0 (property:persist.sys.usb.config=*)
<6>[   11.541439] init: command 'setprop' r=0
<6>[   11.541457] init: processing action 0x2c068 (property:ro.debuggable=1)
<5>[   11.542256] init: starting 'console'
<6>[   11.542519] init: command 'start' r=0
<6>[   11.542559] init: processing action 0x350b0 (property:ro.debuggable=1)
<5>[   11.542598] init: starting 'adbd'
<6>[   11.542851] init: command 'start' r=0
<6>[   11.542870] init: processing action 0x31a08 (property:sys.usb.config=mass_storage,adb)
<6>[   11.542883] init: command 'start' r=0
<6>[   11.542918] init: command 'setprop' r=0
<6>[   11.558802] warning: `adbd' uses 32-bit capabilities (legacy support in use)
<6>[   11.558869] enabling adb
<6>[   11.603342] adb_open
<7>[   11.606522] onenand_wait: correctable ECC error = 0x0002
<6>[   11.775389] init: waitpid returned pid 153, status = 00000000
<5>[   11.775409] init: process 'gpsd', pid 153 exited
<6>[   12.071530] android_usb gadget: high speed config #1: android
<6>[   12.338662] s3cfb s3cfb: [fb0] dma: 0x42f04000, cpu: 0xeb800000, size: 0x00465000
<5>[   12.344240] init: starting 'bootanim'

root@android:/ # md5sum /system/vendor/bin/samsung-gpsd
870a5d6f3542fd7421b215fcb37d884c  /system/vendor/bin/samsung-gpsd

Similar excerpt from CM9/Aries:

<6>[   17.773439] init: command 'setprop' r=0
<6>[   17.820110] init: processing action 0x31cc8 (queue_property_triggers)
<6>[   17.851408] init: command 'queue_property_triggers' r=0
<6>[   17.870859] init: processing action 0x2b778 (nonencrypted)
<5>[   17.898457] init: starting 'gpsd'
<5>[   17.900824] init: starting 'geomagneticd'
<6>[   17.921944] init: Created socket '/dev/socket/gps' with mode '660', user '1021', group '1000'
<5>[   17.929572] init: starting 'tvout'
<6>[   17.932675] init: command 'class_start' r=0
<6>[   17.984177] init: processing action 0x2bea0 (property:persist.sys.usb.config=*)
<6>[   18.023304] init: command 'setprop' r=0
<6>[   18.025801] init: processing action 0x2c068 (property:ro.debuggable=1)
<5>[   18.096661] init: starting 'console'
<6>[   18.101724] init: command 'start' r=0
<6>[   18.104049] init: processing action 0x2fec0 (property:sys.usb.config=mass_storage,adb)
<3>[   18.193108] android_usb: already disabled
<6>[   18.210761] init: command 'write' r=0
<6>[   18.213147] init: command 'write' r=0
<6>[   18.257551] init: command 'write' r=0
<6>[   18.259958] init: command 'write' r=0
<6>[   18.292869] adb_bind_config
<6>[   18.300329] android_work: did not send uevent (0 0   (null))
<6>[   18.316124] init: command 'write' r=0
<5>[   18.318439] init: starting 'adbd'
<6>[   18.355612] init: command 'start' r=0
<6>[   18.357917] init: command 'setprop' r=0
<6>[   18.370939] warning: `adbd' uses 32-bit capabilities (legacy support in use)
<6>[   18.421654] adb_open
<6>[   18.606748] s3cfb s3cfb: [fb0] dma: 0x4c45a000, cpu: 0xeb800000, size: 0x00465000
<5>[   18.640476] init: starting 'bootanim'

root@android:/ # md5sum /system/vendor/bin/gpsd
a94ee43de5c0b2ccd0de45d9c404e9f9  /system/vendor/bin/gpsd

_Note: orientationd was seen to be starting "on demand" in an informal check_

**Comment by jeffsf** [comment]
gpio120 and gpio121 seen on both Aries and Herring -- no max8998-charger/power_supply/battery/gps seen on Aries

_This may be a red herring. I seem to remember power_supply/battery/gps being unimplemented functions when I was working on the charging current output for Herring on my local branches._

**Aries:**

root@android:/ # find /sys/ -name '_gps_'  
/sys/devices/virtual/sec/gps
/sys/class/sec/gps
root@android:/ # ls -l /sys/class/sec/gps
lrwxrwxrwx root     root              2012-09-16 13:06 gps -> ../../devices/virtual/sec/gps
root@android:/ # ls -l /sys/dev  
dev/      devices/  
root@android:/ # busybox ls -lR /sys/devices/virtual/sec/gps  
/sys/devices/virtual/sec/gps:
lrwxrwxrwx    1 root     root             0 Sep 16 13:06 GPS_PWR_EN -> ../../gpio/gpio121
lrwxrwxrwx    1 root     root             0 Sep 16 13:06 GPS_nRST -> ../../gpio/gpio120
drwxr-xr-x    2 root     root             0 Sep 16 13:06 power
lrwxrwxrwx    1 root     root             0 Sep 16 13:06 subsystem -> ../../../../class/sec
-rw-r--r--    1 root     root          4096 Sep 16 13:06 uevent

/sys/devices/virtual/sec/gps/power:

**Herring:**

root@android:/ # find /sys/ -name '_gps_'
/sys/devices/platform/i2c-gpio.6/i2c-6/6-0066/max8998-charger/power_supply/battery/gps
/sys/devices/virtual/sec/gps
/sys/class/sec/gps
root@android:/ # ls -lR /sys/devices/virtual/sec/gps

/sys/devices/virtual/sec/gps:
lrwxrwxrwx root     root              2012-09-16 13:27 GPS_PWR_EN -> ../../gpio/gpio121
lrwxrwxrwx root     root              2012-09-16 13:27 GPS_nRST -> ../../gpio/gpio120
-r--r--r-- root     root         4096 2012-09-16 13:27 hwrev
drwxr-xr-x root     root              2012-09-16 13:27 power
lrwxrwxrwx root     root              2012-09-16 13:27 subsystem -> ../../../../class/sec
-rw-r--r-- root     root         4096 2012-09-16 13:27 uevent

/sys/devices/virtual/sec/gps/power:
-rw-r--r-- root     root         4096 2012-09-16 13:27 wakeup
c-gpio.6/i2c-6/6-0066/max8998-charger/power_supply/battery/gps                <
-rw-rw-r-- radio    system       4096 2012-09-16 13:23 gps

**Comment by jeffsf** [comment]
Debugging indicates that the initialization of the cpp linkage between the Android world and the GPS appears to be working. This may be related to the RIL not functioning at this time. Deferring.

**Comment by maxfierke** [comment]
Is this still an issue with the recent RIL fixes?

**Comment by niltmt** [comment]
This gps problem is fixed in the current aries tree. FB is also cleaning up the vendor blobs to keep the relevant gps blobs only. So cheer! :p
