### ISSUE TITLE
Minor Bug

### ISSUE THREAD

**Issue by Yassir5505** [teamacid/android_device_samsung_galaxys4gmtd#33]
When you go to Settings> Lock screen> Calendar,the setting app force closes every time.

I know this isn't a big deal but i want to help and i hope this can be fixed or removed from rom completely so we can one day make this rom official.

**Comment by bhundven** [comment]
This is probably a bug fixed upstream. I'm gonna sync my source soon and release a new build.
This isn't a bug with our port, it's a bug with CM.

You probably need to report the bug CyanogenMod: http://code.google.com/p/cyanogenmod/issues/list

**Comment by Yassir5505** [comment]
Oh im so sorry i didn't know, i will report it to CM right now.Thanks for your help. =)

**Comment by bhundven** [comment]
No worries!

**Comment by Fluidification** [comment]
Don´t have this issue, therefore, it can´t be confirmed

Running R8 CM9.1.0

**Comment by bhundven** [comment]
Not my problem.

**Comment by Yassir5505** [comment]
It turns out that its not a bug and i made a mistake. I disabled the apps called "calendar storage" and "calendar" because i downloaded a new calendar app made by Google. After i enabled the "calendar storage" app everything worked again. So i just wanted to say that there is no bug, that it was my fault, and i'm sorry for troubling you guys.
